# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161019135521 on 2016-10-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_tipo', models.CharField(max_length=200)),
                ('categoria_relacion', models.ManyToManyField(to='goal.Goal')),
            ],
        ),
    ]
