# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='static/files')),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
